### ISSUE TITLE
Subject startFrame and bValid in data

### ISSUE THREAD

**Issue by chiragraman** [CMU-Perceptual-Computing-Lab/ssp#2]
Hello!

I noticed that in addition to the `startFrame` in the pickled dictionary for each group, there is an entry for the start frame in the data dictionary for each subject as well. These don't match, so I am assuming that the start frame in the subject dictionary represents the first frame where they are visible in the scene. However, the data array for each subject has the same shape. 

So I am wondering if the data is represented starting at the start frame for the haggling game, or the start frame mentioned in the data dictionary. Here is a running example using seq `170221_haggling_b1_group0`:

```
In [23]: with open("170221_haggling_b1_group0.pkl", "rb") as f:
        ...:     data = pickle.load(f, encoding="latin1")

In [24]: data["startFrame"]
Out[24]: 1223

In [25]: data["subjects"][0].keys()
Out[25]: dict_keys(['joints19', 'bodyNormal', 'faceNormal', 'humanId', 'scores', 'startFrame', 'bValid'])

In [26]: data["subjects"][0]["startFrame"]
Out[26]: 1167

In [27]: data["subjects"][1]["startFrame"]
Out[27]: 1078

In [28]: data["subjects"][2]["startFrame"]
Out[28]: 1125

In [29]: data["subjects"][0]["bodyNormal"].shape
Out[29]: (3, 1832)

In [30]: data["subjects"][0]["joints19"].shape
Out[30]: (57, 1832)

In [31]: data["subjects"][1]["bodyNormal"].shape
Out[31]: (3, 1832)

In [32]: 1223 + 1832
Out[32]: 3055
```

Downloading the video for the sequence and extracting the individual frames, it seems like the participants start leaving shortly after frame 3055, leading me to believe that the data in the `subjects` dictionary is for the frames explicitly involving the game, and the `startFrame` in the subject dictionary is just auxiliary information not pertaining to the data. 

On the same note of auxiliary data, how should one interpret bValid? It's a single boolean while the scores are provided for each frame, so I'm not sure how the two pieces combine.

Can someone confirm/clarify these please? Thanks!

**Comment by jhugestar** [comment]
Hi @chiragraman,

Thanks for your interest and question (and sorry for my delayed response...due to many deadlines :( )

0. the "frame" here means basically HD video frames  (VGA has different frame indexing and frame rate)
1. The original panoptic db (json) processed each frame separately, but it has a unique human ID for each individual. I first aggregate the motion data of the same individual across frames (using the human ID) and saved it as a single pkl. The "startFrame" is the frame when the individual's motion data appeared for the first time (the time when the person entered the dome). Thus, it's different for each individual. 
2. Sometimes we lost the skeleton of the target individual (e.g., due to a severe occlusion) in the middle of the game, and then we have blank data for the frames where we have  ['bValid'] == False. 

This code would be helpful to understand above part:
https://github.com/CMU-Perceptual-Computing-Lab/socialSignalPred/blob/ff099018d7ef83a2b91fa5c9b5fba21b8111c805/motionsynth_data/data/processed_panoptic/gathering_panopticDB_body.py#L50


3. I manually annotated the frame where each game started (the time all participants started negotiation). The data["startFrame"] is basically this. You may noticed that this time is later than the startFrames of all individuals, which makes sense since the game started after all people entered the system. 

4. For the 170221_haggling_b1_group0 file, I trimmed the data so that they have start time and the duration are the same, for convenience (that's why you see the same length of numpy data). 


This code would be helpful to understand this:
https://github.com/CMU-Perceptual-Computing-Lab/socialSignalPred/blob/ff099018d7ef83a2b91fa5c9b5fba21b8111c805/motionsynth_data/data/processed_panoptic/process_hagglingDB_body.py#L135

**Comment by chiragraman** [comment]
@jhugestar Just wanted to confirm one thing about bValid. If I am not mistaken, this assert you have later in the code should have failed if any of the frames had missed a skeleton.

https://github.com/CMU-Perceptual-Computing-Lab/socialSignalPred/blob/ff099018d7ef83a2b91fa5c9b5fba21b8111c805/motionsynth_data/data/processed_panoptic/gathering_panopticDB_body.py#L67-L72

I think the shape of the joints before being appended can only not match if a new pose was added (causing the bValid to be false for all the people except the new one), and then in the subsequent frame features were added for the person for whom bValid was previously false. 

If the final data was generated with the assert in there, is it safe to assume that you wouldn't have missed skeletons in the data in this repo? I'll check nevertheless in the code, just wanted to make sure conceptually (which is why I have already closed the issue since it answers the original question).
